

elasticsearch:
  host: localhost
  port: 9200
  username: ${name_to_elastic}
  password: ${password_to_elastic}
  use-ssl: true
  truststore-path: classpath:elasticsearch-truststore.jks
  truststore-password: ${password_to_certificate}

server:
  port: 8081