

elasticsearch:
  host: localhost
  port: 9200
  username: ${name_to_elastic}
  password: ${password_to_elastic}
  use-ssl: true
  truststore-path: classpath:elasticsearch-truststore.jks
  truststore-password: ${password_to_certificate}

server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:keystore.p12  # путь к .p12 файлу
    key-store-password: changeit  # пароль от .p12
    key-store-type: PKCS12

#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      group-id: updateConsumer_v2
#      auto-offset-reset: earliest
#      properties:
#        spring.json.trusted.packages: "*"
#        spring.json.value.default.type: com.myshop.searchservice.DTO
